import test from 'node:test';
import assert from 'node:assert/strict';
import { renderMarkdownReport } from '../src/report/markdown.js';
import { renderGithubComment } from '../src/report/githubComment.js';
import { docsChecks } from '../src/audit/checks/docs.js';
import { npmBinary, run } from '../src/util/proc.js';
import { TOOL_HOME } from '../src/util/repo.js';

function hasBinary(name) {
  const probe = process.platform === 'win32' ? 'where' : 'which';
  return run(probe, [name]).ok;
}

const linkHealth = docsChecks.find((c) => c.id === 'docs.link_health');

function fakeReport(repoUrl) {
  return {
    project: { name: 'x', repo_url: repoUrl },
    generated_at: '2026-01-01T00:00:00.000Z',
    score: { total: 50, grade: 'F', axes: {} },
    summary: { passedChecks: 1, checks: 2, errors: 0, warnings: 0, info: 0, autofixable: 0 },
    findings: [],
  };
}

function runLinkHealth(linkResults) {
  return linkHealth.run({ options: { online: true }, online: { linkResults } });
}

test('report footers link to the tool, never to the audited repository', () => {
  const audited = 'https://github.com/someone/their-repo';
  const md = renderMarkdownReport(fakeReport(audited));
  assert.match(md, /Generated by `repo-aeo` — https:\/\/github\.com\/WhiteBite\/repo-aeo/);
  assert.ok(!md.includes(audited));

  const comment = renderGithubComment(fakeReport(audited));
  assert.match(comment, new RegExp(`<a href="${TOOL_HOME.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}">Repo Discoverability Kit</a>`));
  assert.ok(!comment.includes(audited));
});

test('github-comment escapes HTML in finding text; the markdown renderer does not', () => {
  const report = {
    project: { name: 'x' },
    generated_at: '2026-01-01T00:00:00.000Z',
    score: { total: 50, grade: 'F', axes: {} },
    summary: { passedChecks: 1, checks: 2, errors: 2, warnings: 0, info: 0, autofixable: 0 },
    findings: [
      { id: 'readme.quickstart', axis: 'readme', severity: 'error', weight: 5, effort: 'S', title: '<script>alert(1)</script> in README', why: 'why <b>bold</b> & more', fix: 'fix <i>it</i> & that', autoFixable: false },
      { id: 'docs.llms', axis: 'docs', severity: 'warn', weight: 3, effort: 'S', title: 'llms.txt drift <img src=x>', why: 'stale', fix: 'regenerate', autoFixable: false },
    ],
  };

  const comment = renderGithubComment(report, { maxFindings: 1 });
  assert.ok(comment.includes('&lt;script&gt;alert(1)&lt;/script&gt;'), 'the title must be fully escaped');
  assert.ok(!comment.includes('<script>'), 'raw <script> must not survive');
  assert.ok(!comment.includes('<b>'), 'raw <b> must not survive');
  assert.ok(!comment.includes('<img src=x>'), 'the details-section title must be escaped too');
  assert.ok(comment.includes('&lt;img src=x&gt;'));
  assert.ok(comment.includes('&amp; more'));
  assert.ok(comment.includes('&amp; that'));

  const md = renderMarkdownReport(report);
  assert.ok(md.includes('<script>alert(1)</script>'), 'markdown is not HTML and must stay unescaped');
});

test('a rate-limited link (429) is a warning, not a broken link', () => {
  const result = runLinkHealth([{ url: 'https://deepwiki.com', status: 429, ok: false, error: null }]);
  assert.equal(result.severity, 'warn');
  assert.match(result.title, /rate-limited/);
});

test('a dead link stays an error and mentions rate-limited neighbours', () => {
  const result = runLinkHealth([
    { url: 'https://gone.example', status: 404, ok: false, error: null },
    { url: 'https://deepwiki.com', status: 429, ok: false, error: null },
  ]);
  assert.equal(result.severity, 'error');
  assert.match(result.fix, /gone\.example \(404\)/);
  assert.match(result.fix, /plus 1 rate-limited/);
});

test('healthy links produce no finding', () => {
  assert.equal(runLinkHealth([{ url: 'https://ok.example', status: 200, ok: true, error: null }]), null);
});

test('npmBinary resolves a spawnable npm on this platform', (t) => {
  if (!hasBinary('npm')) return t.skip('npm not installed');
  const win = process.platform === 'win32';
  assert.equal(npmBinary(), win ? 'npm.cmd' : 'npm');
  const result = run(npmBinary(), ['--version'], { timeout: 30000, shell: win });
  assert.equal(result.ok, true, result.stderr);
  assert.match(result.stdout.trim(), /^\d+\./);
});
