/** Markdown renderer for the full audit report (`rdk audit --format markdown`). */
import { AXIS_LABELS } from '../audit/score.js';
import { TOOL_HOME } from '../util/repo.js';

const SEVERITY_BADGE = { error: 'ERROR', warn: 'WARN', info: 'INFO' };

function scoreBar(score) {
  const filled = Math.round(score / 5);
  return `${'█'.repeat(filled)}${'░'.repeat(20 - filled)} ${score}/100`;
}

export function renderMarkdownReport(report) {
  const lines = [];
  const { score, summary, findings } = report;

  lines.push(`# Discoverability audit — ${report.project.name || 'unknown project'}`);
  lines.push('');
  lines.push(`**Score: ${score.total}/100 (grade ${score.grade})** — generated ${report.generated_at}`);
  lines.push('');
  lines.push(scoreBar(score.total));
  lines.push('');
  lines.push('| Axis | Score | Weight | Status |');
  lines.push('| --- | --- | --- | --- |');
  for (const [axis, data] of Object.entries(score.axes)) {
    const status = !data.applicable ? 'n/a' : data.score === 100 ? 'complete' : `${data.passed}/${data.total} checks passed`;
    lines.push(`| ${AXIS_LABELS[axis] || axis} | ${data.applicable ? `${data.score}/100` : '—'} | ${data.applicable ? data.weight : '—'} | ${status} |`);
  }
  lines.push('');
  lines.push(`Checks: ${summary.passedChecks}/${summary.checks} passed · errors ${summary.errors} · warnings ${summary.warnings} · info ${summary.info} · autofixable ${summary.autofixable}`);
  lines.push('');

  if (report.config_warnings && report.config_warnings.length > 0) {
    lines.push('## Config warnings');
    lines.push('');
    for (const warning of report.config_warnings) lines.push(`- ${warning.message}`);
    lines.push('');
  }

  for (const severity of ['error', 'warn', 'info']) {
    const group = findings.filter((f) => f.severity === severity);
    if (group.length === 0) continue;
    lines.push(`## ${SEVERITY_BADGE[severity]} (${group.length})`);
    lines.push('');
    for (const f of group) {
      lines.push(`### ${f.title}`);
      lines.push('');
      lines.push(`- **id:** \`${f.id}\` · **axis:** ${AXIS_LABELS[f.axis] || f.axis} · **effort:** ${f.effort}${f.autoFixable ? ' · **autofixable**' : ''}`);
      lines.push(`- **why:** ${f.why}`);
      lines.push(`- **fix:** ${f.fix}`);
      lines.push('');
    }
  }

  if (findings.length === 0) {
    lines.push('## Nothing to improve');
    lines.push('');
    lines.push('Every applicable discoverability check passes. Re-run after the next feature change.');
    lines.push('');
  }

  lines.push('## Suggested patch order');
  lines.push('');
  const ordered = [...findings].sort((a, b) => {
    const rank = { error: 0, warn: 1, info: 2 };
    return rank[a.severity] - rank[b.severity] || b.weight - a.weight;
  });
  if (ordered.length === 0) {
    lines.push('1. No patches needed.');
  } else {
    ordered.slice(0, 12).forEach((f, index) => {
      lines.push(`${index + 1}. \`${f.id}\` — ${f.fix} (effort ${f.effort}${f.autoFixable ? ', autofix' : ''})`);
    });
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`Generated by \`repo-aeo\` — ${TOOL_HOME}`);
  lines.push('');
  return lines.join('\n');
}

export default { renderMarkdownReport };
